name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Ensure labels exist
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh label delete "bug" --yes || true
          gh label delete "documentation" --yes || true
          gh label delete "duplicate" --yes || true
          gh label delete "enhancement" --yes || true
          gh label delete "good first issue" --yes || true
          gh label delete "help wanted" --yes || true
          gh label delete "invalid" --yes || true
          gh label delete "question" --yes || true
          gh label delete "wontfix" --yes || true

          gh label create "ğŸš¨ action" --description "Changes in GitHub workflows or actions" --color "A75AD5" --force
          gh label create "ğŸ¤– bot" --description "Automatically generated pull request" --color "0075CA" --force
          gh label create "ğŸ› bug" --description "Something isn't working" --color "D73A4A" --force
          gh label create "ğŸ“ changeset" --description "Contains changeset files" --color "304EF9" --force
          gh label create "ğŸš§ config" --description "Configuration file updates" --color "C0ED4F" --force
          gh label create "âœ’ï¸ documentation" --description "Documentation updates, like README changes" --color "66741D" --force
          gh label create "ğŸ” duplicate" --description "This issue or pull request already exists" --color "008672" --force
          gh label create "â« enhancement" --description "New feature or request" --color "3C11FD" --force
          gh label create "ğŸ¥‡ good first issue" --description "Good for newcomers" --color "7057FF" --force
          gh label create "ğŸ†˜ help wanted" --description "Extra attention is needed" --color "BFD4F2" --force
          gh label create "ğŸŒ i18n" --description "Updates to internationalized docs, excluding English" --color "006B75" --force
          gh label create "ğŸ‘€ invalid" --description "This doesn't seem right" --color "E4E669" --force
          gh label create "ğŸš€ manifest" --description "Manifest-related changes" --color "96D3D7" --force
          gh label create "ğŸ“¦ package" --description "Updates in package structure or package.json" --color "F34A37" --force
          gh label create "â“ question" --description "Further information is requested" --color "D876E3" --force
          gh label create "ğŸ¯ styles" --description "Stylesheets or design updates" --color "550F5A" --force
          gh label create "ğŸ”’ wontfix" --description "This will not be worked on" --color "FFFFFF" --force

      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: true
