name: WelcomeBot

on:
  pull_request_target:
    branches: [main]
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome:
    name: Welcome First-Time Contributors
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Convert Repository Name to Title Case
        id: convert_repo_name
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          TITLE_CASE_REPO_NAME=$(echo "$REPO_NAME" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))} 1')
          echo "title_case_repo_name=$TITLE_CASE_REPO_NAME" >> $GITHUB_ENV
      - uses: zephyrproject-rtos/action-first-interaction@58853996b1ac504b8e0f6964301f369d2bb22e5c
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          pr-opened-message: |
            Hello! Thank you for opening your **first PR** to ${{ env.title_case_repo_name }}! ✨

            Here’s what will happen next:

            1. Our GitHub bots will run to check your changes.
               If they spot any issues you will see some error messages on this PR.
               Don’t hesitate to ask any questions if you’re not sure what these mean!

            2. One or more of our maintainers will take a look and may ask you to make changes.
               We try to be responsive, but don’t worry if this takes a few days.
